version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: financing-mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: financing_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user-password

    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3307:3306"

volumes:
  db-data:
